
- name: "create repository vars for: {{BITBUCKET_REPOSITORY}}"
  juanenriqueescobar.bitbucket.repository_var:
    username:    "{{BITBUCKET_USERNAME}}"
    password:    "{{BITBUCKET_PASSWORD}}"
    repository:  "{{BITBUCKET_REPOSITORY}}"      
    state:       "present"
    var_name:    "{{__loop_var.name}}"
    var_value:   "{{__loop_var.value}}"
    var_secured: "{{__loop_var.secured}}"
  loop:          "{{REPOSITORY_VARS}}" 
  loop_control:
    label:    "{{__loop_var.name}}"
    loop_var: "__loop_var"
      
- name: "create deployment for: {{BITBUCKET_REPOSITORY}}"
  juanenriqueescobar.bitbucket.deployment:
    username:   "{{BITBUCKET_USERNAME}}"
    password:   "{{BITBUCKET_PASSWORD}}"
    repository: "{{BITBUCKET_REPOSITORY}}"      
    deployment: "{{DEPLOYMENT_NAME}}"
    state:      "present"
    type:       "{{DEPLOYMENT_TYPE}}"

- name: "create deployment pattern for: {{BITBUCKET_REPOSITORY}}"
  juanenriqueescobar.bitbucket.deployment_pattern:
    username:   "{{BITBUCKET_USERNAME}}"
    password:   "{{BITBUCKET_PASSWORD}}"
    repository: "{{BITBUCKET_REPOSITORY}}"
    deployment: "{{DEPLOYMENT_NAME}}"
    state:      "present"
    pattern:    "{{DEPLOYMENT_PATTERN}}"

- name: "create deployment vars for: {{BITBUCKET_REPOSITORY}}"
  juanenriqueescobar.bitbucket.deployment_var:
    username:    "{{BITBUCKET_USERNAME}}"
    password:    "{{BITBUCKET_PASSWORD}}"
    repository:  "{{BITBUCKET_REPOSITORY}}"      
    deployment:  "{{DEPLOYMENT_NAME}}"
    state:       "present"
    var_name:    "{{__loop_var.name}}"
    var_value:   "{{__loop_var.value}}"
    var_secured: "{{__loop_var.secured}}"
  loop:          "{{DEPLOYMENT_VARS}}" 
  loop_control:
    label:    "{{__loop_var.name}}"
    loop_var: "__loop_var"
