- name: "enable pipelines in the repository"
  juanenriqueescobar.bitbucket.pipelines_enabled:
    username:   "{{BITBUCKET_USERNAME}}"
    password:   "{{BITBUCKET_PASSWORD}}"
    repository: "{{BITBUCKET_REPOSITORY}}"
    state:      "present"

- name: "create repository vars for: {{BITBUCKET_REPOSITORY}}"
  juanenriqueescobar.bitbucket.repository_var:
    username:    "{{BITBUCKET_USERNAME}}"
    password:    "{{BITBUCKET_PASSWORD}}"
    repository:  "{{BITBUCKET_REPOSITORY}}"
    state:       "{{__loop_var.state | default('present') }}"
    var_name:    "{{__loop_var.name }}"
    var_value:   "{{__loop_var.value}}"
    var_secured: "{{__loop_var.secured}}"
  loop:          "{{REPOSITORY_VARS}}" 
  loop_control:
    label:    "{{__loop_var.name}}"
    loop_var: "__loop_var"
      
- include_tasks: deployment.yml
  loop: "{{DEPLOYMENTS}}"
  loop_control:
    label:    "{{__loop_var_1.DEPLOYMENT_NAME}}"
    loop_var: "__loop_var_1"
